### ISSUE TITLE
Title of the homepage is blank

### ISSUE THREAD

**Issue by gaato** [gaato/gaato.net#22]
`title` tag in the generated homepage html is blank. Why?
<img width="119" alt="スクリーンショット 2022-12-01 12 44 55" src="https://user-images.githubusercontent.com/57865205/204961034-775b6c21-b4d1-4eca-ae63-1723f0b9267a.png">

**Comment by sidd6p** [comment]
Hey, I think I can fix this.
Would you like to assign this to time

**Comment by gaato** [comment]
@sidd6p Yes, please. I'm not in a hurry. Thank you.
